### ISSUE TITLE
Create shopping cart with add/delete functions

### ISSUE THREAD

**Issue by ryan7blanc** [ryan7blanc/ezshop#2]
Shopping cart must allow users to add products or take products off of the cart. When viewing the cart, the user can also view the total price of the purchase.

**Comment by bebu8967** [comment]
We could add a quick checkout feature using an Google pay or Apple Pay API where the user has all their information pre loaded

**Comment by annasouk** [comment]
Also, adding a product will probably be a POST request and removing a product from the cart will be a DELETE request to the server.
